=== Makeouthill2055/XML-Project/19031758_Manzil_Katwal.dtd
<!ELEMENT BookStore (storeName,Address,website,contact,Books)>
<!ATTLIST BookStore
 Branch NMTOKEN #REQUIRED
 xmlns:xsi CDATA #REQUIRED
xsi:noNamespaceSchemaLocation CDATA #REQUIRED
>
<!ELEMENT storeName (#PCDATA)>
<!ELEMENT Address (#PCDATA)>
<!ATTLIST Address streetName NMTOKEN #REQUIRED>
<!ELEMENT website (#PCDATA)>
<!ELEMENT contact (email,contactNo.)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT contactNo. (#PCDATA)>
<!ELEMENT Books (Book+)>
<!ELEMENT Book (Title,CoverArtist,price,Publisher+,PublishYear,Pages,ISBN,Size,MediaType+,Authors)>
<!ATTLIST Book Category CDATA #REQUIRED>
<!ELEMENT Title (#PCDATA)>
<!ATTLIST Title Language CDATA #REQUIRED>
<!ELEMENT CoverArtist (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ATTLIST price Currency NMTOKEN #IMPLIED>
<!ATTLIST price currency CDATA #IMPLIED>
<!ELEMENT Publisher (#PCDATA)>
<!ATTLIST Publisher Country NMTOKEN #REQUIRED>
<!ELEMENT PublishYear (#PCDATA)>
<!ELEMENT Pages (#PCDATA)>
<!ELEMENT ISBN (#PCDATA)>
<!ELEMENT Size (#PCDATA)>
<!ELEMENT MediaType (#PCDATA)>
<!ELEMENT Authors (Author)>
<!ELEMENT Author (Name,Born,BirthPlace,AlmaMater?,Period,Spouse,Genre,NotableWorks,socialMedia)>
<!ATTLIST Author Title (Mr|Mrs) #REQUIRED>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Born (#PCDATA)>
<!ATTLIST Born Age NMTOKEN #IMPLIED>
<!ATTLIST Born age NMTOKEN #IMPLIED>
<!ELEMENT BirthPlace (#PCDATA)>
<!ELEMENT AlmaMater (#PCDATA)>
<!ELEMENT Period (#PCDATA)>
<!ELEMENT Spouse (#PCDATA)>
<!ELEMENT Genre (#PCDATA)>
<!ATTLIST Genre Favourite NMTOKEN #REQUIRED>
<!ELEMENT NotableWorks (#PCDATA)>
<!ELEMENT socialMedia (Facebook)>
<!ELEMENT Facebook (FacebookID,FacebookFollowers,FacebookFollowing,FacebookJoined)>
<!ATTLIST Facebook Status (Active|InActive) #REQUIRED>
<!ELEMENT FacebookID (#PCDATA)>
<!ELEMENT FacebookFollowers (#PCDATA)>
<!ELEMENT FacebookFollowing (#PCDATA)>
<!ELEMENT FacebookJoined (#PCDATA)>

=== Makeouthill2055/XML-Project/19031758_Manzil_Katwal.xml
<?xml version="1.1" encoding="UTF-8"?>
<!DOCTYPE BookStore SYSTEM "19031758_Manzil_Katwal.dtd">
<BookStore Branch="Itahari"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="19031758_venetianblind.xsd" >
    <storeName>ItahariBookStor</storeName>
    <Address streetName="SainikMarga">Itahari</Address>
    <website>www.ItahariStore.com.np</website>
    <contact>
        <email>www.itaharistore@gmail.com</email>
        <contactNo.>9815645239</contactNo.>
    </contact>
    <Books>
        <Book Category="Fantasy">
            <Title Language="English">Harry Potter and the Philosopher's Stone</Title>
            <CoverArtist></CoverArtist>
            <price Currency="USD">160USD</price>
            <Publisher Country="UK">Bloomsbury</Publisher>
            <Publisher Country="US">Scholastic</Publisher>
            <PublishYear>1997</PublishYear>
            <Pages>223</Pages>
            <ISBN>0-7475-3269-9</ISBN>
            <Size>5 x 0.75 x 8 inches</Size>
            <MediaType>audioBook</MediaType>
            <MediaType>e-Book</MediaType>
            <Authors>
                <Author Title="Mrs">
                    <Name>J.K. Rowling</Name>
                    <Born Age="55">1965-07-31</Born>
                    <BirthPlace>England</BirthPlace>
                    <AlmaMater>University of Exeter</AlmaMater>
                    <Period>1997 to present</Period>
                    <Spouse>Neil Murray</Spouse>
                    <Genre Favourite="Fantasy">Drama</Genre>
                    <NotableWorks>HarryPotter Series</NotableWorks>
                    <socialMedia>
                        <Facebook Status="Active">
                            <FacebookID>J.K. Rowling</FacebookID>
                            <FacebookFollowers>6.6M</FacebookFollowers>
                            <FacebookFollowing>200</FacebookFollowing>
                            <FacebookJoined>2012</FacebookJoined>
                        </Facebook>
                    </socialMedia>
                </Author>
            </Authors>
         </Book>
         <Book Category="Quest">
            <Title Language="Portuguese">O Alquimista</Title>
            <CoverArtist>Caravaggio</CoverArtist>
            <price Currency="USD">160</price>
            <Publisher Country="Portugal">HarperTorch </Publisher>
            <PublishYear>1988</PublishYear>
            <Pages>163</Pages>
            <ISBN>0-06-250217-4</ISBN>
            <Size>5.10(w) x 7.90(h) x 1.10(d)</Size>
            <MediaType>Print HardBack</MediaType>
            <Authors>
                <Author Title="Mr">
                    <Name>Paulo Coelho de Souza</Name>
                    <Born Age="73">1947-08-24</Born>
                    <BirthPlace>Brazil</BirthPlace>
                    <Period>1974 to present</Period>
                    <Spouse>Christina Oiticica</Spouse>
                    <Genre Favourite="Romance">Drama</Genre>
                    <NotableWorks>O Alquimista</NotableWorks>
                    <socialMedia>
                        <Facebook Status="InActive">
                            <FacebookID>Paulo Coelho</FacebookID>
                            <FacebookFollowers>41,320</FacebookFollowers>
                            <FacebookFollowing>260</FacebookFollowing>
                            <FacebookJoined>2012</FacebookJoined>
                        </Facebook>
                    </socialMedia>
                </Author>
            </Authors>
         </Book>
    </Books>
 </BookStore>
